version: "3"

services:
  
  mysql-master:  
    image: mysql:8.0
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projekt 
      MYSQL_USER: mirror_user 
      MYSQL_PASSWORD: mirror_root
    
    ports:
      - "3310:3306"


  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave

    depends_on:
      - mysql-master

    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projekt
      MYSQL_USER: mirror_user
      MYSQL_PASSWORD: mirror_root

    ports:
      - "3311:3306"
 
